title: Ilija Krišto Floppsy # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mail: ilijakristo01@gmail.com
  <br><br>
  Phone: 00 385 95 573 3772
  <br><br>
  Adress: Put Zagoraca 11, Kaštel Novi
  <br><br>
  My biggest passion in Unity is visual effects and the things you can do with them is like my will to learn more, incalculable.
  <br><br>
  <a href="https://www.linkedin.com/in/ilija-kri%C5%A1to-75824a231/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
