title: Ilija Krišto Floppsy # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionet Unity game designer from Croatia. I love working and learning.
  <br><br>
  Level design is one of the things that made me love game design even more. It's impactful and it can be as perfect as you want it to be.
  <br><br>
  My biggest passion in Unity is visual effects and the things you can do with them is like my will to learn more, incalculable.
  <br><br>
  <a href="https://www.linkedin.com/in/ilija-kri%C5%A1to-75824a231/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
